#!/usr/bin/env bash
#Configure a new Nginx server so that /redirect_me is redirecting to another page

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello World" | sudo tee /var/www/html/index
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://google.com permanent;' /etc/nginx/sites-available/default
service nginx restart
